### ISSUE TITLE
A question about datasets

### ISSUE THREAD

**Issue by goruiqi** [yg-smile/RL_VVC_dataset#5]
Hello, I have a question about datasets. 

After reading the program, I have the following understanding. In "RL_VVC_dataset-master\data\processed\first_2897_ami_aggto_580", they are  London smart meter dataset, which sent to OpenDSS to calculate power flow. In "RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load", they are uesed to be a part of states at every iteration between agents and the environment.
So, I want to ask if my understanding is correct. If correct, I think the load data uesd to claculate power flow and used as states should be same.

I'm looking forward to your reply.

**Comment by yg-smile** [comment]
Dear @goruiqi , thank you for your read.

Yes your understanding is correct. But I should mention two minor differences ..

1. The `first_2897_ami_aggto_580` is multiplied by a base value before calculating the power flow. These base values are the standard IEEE test feeder snapshot load. We want to multiply that base value because the spatial loading pattern can be preserved ..  These are the relevant lines ..
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/49927412/164836280-761d4351-5055-4364-80c7-50b021774a06.png">
The `_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load_` is already the result of multiplying. So there is no need to multiply again.

2. the values of `_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load_` has been rounded to the 1-st decimal place, to align with the real world meter precision..

The results in `_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\_` assumes the VVC device status is calculated by the legacy control. So please use the load from `first_2897_ami_aggto_580` when the VVC action is obtained by your RL algorithm ..

**Comment by goruiqi** [comment]
Thank you, but I can't understand this clearly. Please allow me to ask a question. 

I print the load data of  "_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load_" and "_first_2897_ami_aggto_580_", and find them are diffrent. If I want use the data in "_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\_" to calculate baseline_reward to make a comparison, all I need to do is that change the load data, which use the data of "_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load_" as the input of the RL model. 

Maybe I don't know the whole program clearly enough. I'm looking forward to your reply.

**Comment by yg-smile** [comment]
Sorry about the confusion.

Yes they are different:

`RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load = first_2897_ami_aggto_580 * load_base`

For example, `load_base` for the 13-bus feeder is: (https://cmte.ieee.org/pes-testfeeders/resources/)
<img width="649" alt="image" src="https://user-images.githubusercontent.com/49927412/164954149-a688f993-6459-4543-8cf4-9ee762725d43.png">

Could you elaborate on the question "all I need to do is that change the load data"? I'm looking forward to your reply.

**Comment by goruiqi** [comment]
Thank you for the quick reply. And I'm sorry, I didn't say it clearly.

1. If I want use the data in "_RL_VVC_dataset-master\data\processed\13(or 123, 8500)_" to calculate baseline_reward to make a comparison, the input of RL model should be "_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load_". (The program is already like this)
2. Based on the first point, the enviroment need ues the "_RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load_" to calculate the power flow not "RL_VVC_dataset-master\data\processed\first_2897_ami_aggto_580".
3. So, in my point of view, we don't need the datasets  "RL_VVC_dataset-master\data\processed\first_2897_ami_aggto_580".

Is my understanding correct?

**Comment by yg-smile** [comment]
Thank you.

1. Yes the input of RL should be `RL_VVC_dataset-master\data\processed\13(or 123, 8500)\load`
2. Yes.. Not quite. `load` has been rounded to the 1-st decimal place; whereas `first_2897_ami_aggto_580` is not. Thus `load` should be used as input to RL policy/value neural networks; but `first_2897_ami_aggto_580` should be used to calculate power flow. The reason is that the power flow program is intended to mimic a real world circuit so the numbers are raw (un-rounded).. But when training RL, we only access those data through meters. These meters typically have precisions of 1-st decimal place..
3. When calculating power flow, `first_2897_ami_aggto_580` is needed.

**Comment by goruiqi** [comment]
Thank you very much for your reply. I understand it clearly.  

Wish you all the best.
